package com.lian.entity;
// Generated 2016-5-2 18:35:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbBoard generated by hbm2java
 */
public class TbBoard implements java.io.Serializable {

	private int BId;
	private TbBoard tbBoard;
	private String BName;
	private Set tbBoards = new HashSet(0);
	private Set tbRecruits = new HashSet(0);

	public TbBoard() {
	}

	public TbBoard(int BId, String BName) {
		this.BId = BId;
		this.BName = BName;
	}

	public TbBoard(int BId, TbBoard tbBoard, String BName, Set tbBoards, Set tbRecruits) {
		this.BId = BId;
		this.tbBoard = tbBoard;
		this.BName = BName;
		this.tbBoards = tbBoards;
		this.tbRecruits = tbRecruits;
	}

	public int getBId() {
		return this.BId;
	}

	public void setBId(int BId) {
		this.BId = BId;
	}

	public TbBoard getTbBoard() {
		return this.tbBoard;
	}

	public void setTbBoard(TbBoard tbBoard) {
		this.tbBoard = tbBoard;
	}

	public String getBName() {
		return this.BName;
	}

	public void setBName(String BName) {
		this.BName = BName;
	}

	public Set getTbBoards() {
		return this.tbBoards;
	}

	public void setTbBoards(Set tbBoards) {
		this.tbBoards = tbBoards;
	}

	public Set getTbRecruits() {
		return this.tbRecruits;
	}

	public void setTbRecruits(Set tbRecruits) {
		this.tbRecruits = tbRecruits;
	}

}
