package com.lian.entity;
// Generated 2016-5-2 18:35:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbCompanyResume generated by hbm2java
 */
public class TbCompanyResume implements java.io.Serializable {

	private int crsId;
	private TbCompany tbCompany;
	private TbResume tbResume;
	private Date crsDate;

	public TbCompanyResume() {
	}

	public TbCompanyResume(int crsId, TbCompany tbCompany, TbResume tbResume, Date crsDate) {
		this.crsId = crsId;
		this.tbCompany = tbCompany;
		this.tbResume = tbResume;
		this.crsDate = crsDate;
	}

	public int getCrsId() {
		return this.crsId;
	}

	public void setCrsId(int crsId) {
		this.crsId = crsId;
	}

	public TbCompany getTbCompany() {
		return this.tbCompany;
	}

	public void setTbCompany(TbCompany tbCompany) {
		this.tbCompany = tbCompany;
	}

	public TbResume getTbResume() {
		return this.tbResume;
	}

	public void setTbResume(TbResume tbResume) {
		this.tbResume = tbResume;
	}

	public Date getCrsDate() {
		return this.crsDate;
	}

	public void setCrsDate(Date crsDate) {
		this.crsDate = crsDate;
	}

}
