package com.lian.entity;
// Generated 2016-5-2 18:35:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbNews generated by hbm2java
 */
public class TbNews implements java.io.Serializable {

	private int neId;
	private TbCompany tbCompany;
	private TbUser tbUser;
	private String neTitle;
	private Date neDate;
	private String neContent;

	public TbNews() {
	}

	public TbNews(int neId, TbCompany tbCompany, TbUser tbUser, Date neDate, String neContent) {
		this.neId = neId;
		this.tbCompany = tbCompany;
		this.tbUser = tbUser;
		this.neDate = neDate;
		this.neContent = neContent;
	}

	public TbNews(int neId, TbCompany tbCompany, TbUser tbUser, String neTitle, Date neDate, String neContent) {
		this.neId = neId;
		this.tbCompany = tbCompany;
		this.tbUser = tbUser;
		this.neTitle = neTitle;
		this.neDate = neDate;
		this.neContent = neContent;
	}

	public int getNeId() {
		return this.neId;
	}

	public void setNeId(int neId) {
		this.neId = neId;
	}

	public TbCompany getTbCompany() {
		return this.tbCompany;
	}

	public void setTbCompany(TbCompany tbCompany) {
		this.tbCompany = tbCompany;
	}

	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	public String getNeTitle() {
		return this.neTitle;
	}

	public void setNeTitle(String neTitle) {
		this.neTitle = neTitle;
	}

	public Date getNeDate() {
		return this.neDate;
	}

	public void setNeDate(Date neDate) {
		this.neDate = neDate;
	}

	public String getNeContent() {
		return this.neContent;
	}

	public void setNeContent(String neContent) {
		this.neContent = neContent;
	}

}
