package com.lian.entity;
// Generated 2016-5-2 18:35:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TbResume generated by hbm2java
 */
public class TbResume implements java.io.Serializable {

	private int rsId;
	private TbUser tbUser;
	private TbResume tbResume;
	private String rsType;
	private int rsMoney;
	private String rsEva;
	private int rsFlag;
	private Set tbCompanyResumes = new HashSet(0);
	private Set tbResumes = new HashSet(0);

	public TbResume() {
	}

	public TbResume(int rsId, TbUser tbUser, String rsType, int rsFlag) {
		this.rsId = rsId;
		this.tbUser = tbUser;
		this.rsType = rsType;
		this.rsFlag = rsFlag;
	}

	public TbResume(int rsId, TbUser tbUser, TbResume tbResume, String rsType, int rsMoney, String rsEva,
			int rsFlag, Set tbCompanyResumes, Set tbResumes) {
		this.rsId = rsId;
		this.tbUser = tbUser;
		this.tbResume = tbResume;
		this.rsType = rsType;
		this.rsMoney = rsMoney;
		this.rsEva = rsEva;
		this.rsFlag = rsFlag;
		this.tbCompanyResumes = tbCompanyResumes;
		this.tbResumes = tbResumes;
	}

	public int getRsId() {
		return this.rsId;
	}

	public void setRsId(int rsId) {
		this.rsId = rsId;
	}

	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	public TbResume getTbResume() {
		return this.tbResume;
	}

	public void setTbResume(TbResume tbResume) {
		this.tbResume = tbResume;
	}

	public String getRsType() {
		return this.rsType;
	}

	public void setRsType(String rsType) {
		this.rsType = rsType;
	}

	public int getRsMoney() {
		return this.rsMoney;
	}

	public void setRsMoney(int rsMoney) {
		this.rsMoney = rsMoney;
	}

	public String getRsEva() {
		return this.rsEva;
	}

	public void setRsEva(String rsEva) {
		this.rsEva = rsEva;
	}

	public int getRsFlag() {
		return this.rsFlag;
	}

	public void setRsFlag(int rsFlag) {
		this.rsFlag = rsFlag;
	}

	public Set getTbCompanyResumes() {
		return this.tbCompanyResumes;
	}

	public void setTbCompanyResumes(Set tbCompanyResumes) {
		this.tbCompanyResumes = tbCompanyResumes;
	}

	public Set getTbResumes() {
		return this.tbResumes;
	}

	public void setTbResumes(Set tbResumes) {
		this.tbResumes = tbResumes;
	}

}
