package com.lian.entity;
// Generated 2016-5-2 18:35:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbRecruit generated by hbm2java
 */
public class TbRecruit implements java.io.Serializable {

	private int rcId;
	private TbBoard tbBoard;
	private TbCompany tbCompany;
	private String rcName;
	private String rcDec;
	private String rcNeed;
	private Date rcStarttime;
	private Date rcEndtime;
	private int rcCount;
	private String rcExp;
	private int rcMoney;
	private String rcRecord;
	private Set tbUserRecruits = new HashSet(0);

	public TbRecruit() {
	}

	public TbRecruit(int rcId, TbBoard tbBoard, TbCompany tbCompany, String rcName, Date rcStarttime) {
		this.rcId = rcId;
		this.tbBoard = tbBoard;
		this.tbCompany = tbCompany;
		this.rcName = rcName;
		this.rcStarttime = rcStarttime;
	}

	public TbRecruit(int rcId, TbBoard tbBoard, TbCompany tbCompany, String rcName, String rcDec, String rcNeed,
			Date rcStarttime, Date rcEndtime, int rcCount, String rcExp, int rcMoney, String rcRecord,
			Set tbUserRecruits) {
		this.rcId = rcId;
		this.tbBoard = tbBoard;
		this.tbCompany = tbCompany;
		this.rcName = rcName;
		this.rcDec = rcDec;
		this.rcNeed = rcNeed;
		this.rcStarttime = rcStarttime;
		this.rcEndtime = rcEndtime;
		this.rcCount = rcCount;
		this.rcExp = rcExp;
		this.rcMoney = rcMoney;
		this.rcRecord = rcRecord;
		this.tbUserRecruits = tbUserRecruits;
	}

	public int getRcId() {
		return this.rcId;
	}

	public void setRcId(int rcId) {
		this.rcId = rcId;
	}

	public TbBoard getTbBoard() {
		return this.tbBoard;
	}

	public void setTbBoard(TbBoard tbBoard) {
		this.tbBoard = tbBoard;
	}

	public TbCompany getTbCompany() {
		return this.tbCompany;
	}

	public void setTbCompany(TbCompany tbCompany) {
		this.tbCompany = tbCompany;
	}

	public String getRcName() {
		return this.rcName;
	}

	public void setRcName(String rcName) {
		this.rcName = rcName;
	}

	public String getRcDec() {
		return this.rcDec;
	}

	public void setRcDec(String rcDec) {
		this.rcDec = rcDec;
	}

	public String getRcNeed() {
		return this.rcNeed;
	}

	public void setRcNeed(String rcNeed) {
		this.rcNeed = rcNeed;
	}

	public Date getRcStarttime() {
		return this.rcStarttime;
	}

	public void setRcStarttime(Date rcStarttime) {
		this.rcStarttime = rcStarttime;
	}

	public Date getRcEndtime() {
		return this.rcEndtime;
	}

	public void setRcEndtime(Date rcEndtime) {
		this.rcEndtime = rcEndtime;
	}

	public int getRcCount() {
		return this.rcCount;
	}

	public void setRcCount(int rcCount) {
		this.rcCount = rcCount;
	}

	public String getRcExp() {
		return this.rcExp;
	}

	public void setRcExp(String rcExp) {
		this.rcExp = rcExp;
	}

	public int getRcMoney() {
		return this.rcMoney;
	}

	public void setRcMoney(int rcMoney) {
		this.rcMoney = rcMoney;
	}

	public String getRcRecord() {
		return this.rcRecord;
	}

	public void setRcRecord(String rcRecord) {
		this.rcRecord = rcRecord;
	}

	public Set getTbUserRecruits() {
		return this.tbUserRecruits;
	}

	public void setTbUserRecruits(Set tbUserRecruits) {
		this.tbUserRecruits = tbUserRecruits;
	}

}
