package com.lian.entity;
// Generated 2016-5-2 18:35:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TbUserRecruit generated by hbm2java
 */
public class TbUserRecruit implements java.io.Serializable {

	private int urcId;
	private TbRecruit tbRecruit;
	private TbUser tbUser;
	private Date urcDate;

	public TbUserRecruit() {
	}

	public TbUserRecruit(int urcId, TbRecruit tbRecruit, TbUser tbUser, Date urcDate) {
		this.urcId = urcId;
		this.tbRecruit = tbRecruit;
		this.tbUser = tbUser;
		this.urcDate = urcDate;
	}

	public int getUrcId() {
		return this.urcId;
	}

	public void setUrcId(int urcId) {
		this.urcId = urcId;
	}

	public TbRecruit getTbRecruit() {
		return this.tbRecruit;
	}

	public void setTbRecruit(TbRecruit tbRecruit) {
		this.tbRecruit = tbRecruit;
	}

	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	public Date getUrcDate() {
		return this.urcDate;
	}

	public void setUrcDate(Date urcDate) {
		this.urcDate = urcDate;
	}

}
