package com.lian.entity;
// Generated 2016-5-2 18:35:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbUser generated by hbm2java
 */
public class TbUser implements java.io.Serializable {

	private Integer UId;
	private String UName;
	private String UPassword;
	private String USex;
	private Date UDate;
	private String USchool;
	private String UPrefessional;
	private String URecord;
	private Integer UPhone;
	private String UEmail;
	private Integer UType;
	private Date UBirdate;
	private String URelname;
	private Set tbNewses = new HashSet(0);
	private Set tbResumes = new HashSet(0);
	private Set tbUserRecruits = new HashSet(0);
	private Set tbComments = new HashSet(0);

	public TbUser() {
	}

	public TbUser(Integer UId, String UName, String UPassword, Date UDate, Integer UType) {
		this.UId = UId;
		this.UName = UName;
		this.UPassword = UPassword;
		this.UDate = UDate;
		this.UType = UType;
	}

	public TbUser(Integer UId, String UName, String UPassword, String USex, Date UDate, String USchool,
			String UPrefessional, String URecord, Integer UPhone, String UEmail, Integer UType, Date UBirdate,
			String URelname, Set tbNewses, Set tbResumes, Set tbUserRecruits, Set tbComments) {
		this.UId = UId;
		this.UName = UName;
		this.UPassword = UPassword;
		this.USex = USex;
		this.UDate = UDate;
		this.USchool = USchool;
		this.UPrefessional = UPrefessional;
		this.URecord = URecord;
		this.UPhone = UPhone;
		this.UEmail = UEmail;
		this.UType = UType;
		this.UBirdate = UBirdate;
		this.URelname = URelname;
		this.tbNewses = tbNewses;
		this.tbResumes = tbResumes;
		this.tbUserRecruits = tbUserRecruits;
		this.tbComments = tbComments;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getUName() {
		return this.UName;
	}

	public void setUName(String UName) {
		this.UName = UName;
	}

	public String getUPassword() {
		return this.UPassword;
	}

	public void setUPassword(String UPassword) {
		this.UPassword = UPassword;
	}

	public String getUSex() {
		return this.USex;
	}

	public void setUSex(String USex) {
		this.USex = USex;
	}

	public Date getUDate() {
		return this.UDate;
	}

	public void setUDate(Date UDate) {
		this.UDate = UDate;
	}

	public String getUSchool() {
		return this.USchool;
	}

	public void setUSchool(String USchool) {
		this.USchool = USchool;
	}

	public String getUPrefessional() {
		return this.UPrefessional;
	}

	public void setUPrefessional(String UPrefessional) {
		this.UPrefessional = UPrefessional;
	}

	public String getURecord() {
		return this.URecord;
	}

	public void setURecord(String URecord) {
		this.URecord = URecord;
	}

	public Integer getUPhone() {
		return this.UPhone;
	}

	public void setUPhone(Integer UPhone) {
		this.UPhone = UPhone;
	}

	public String getUEmail() {
		return this.UEmail;
	}

	public void setUEmail(String UEmail) {
		this.UEmail = UEmail;
	}

	public Integer getUType() {
		return this.UType;
	}

	public void setUType(Integer UType) {
		this.UType = UType;
	}

	public Date getUBirdate() {
		return this.UBirdate;
	}

	public void setUBirdate(Date UBirdate) {
		this.UBirdate = UBirdate;
	}

	public String getURelname() {
		return this.URelname;
	}

	public void setURelname(String URelname) {
		this.URelname = URelname;
	}

	public Set getTbNewses() {
		return this.tbNewses;
	}

	public void setTbNewses(Set tbNewses) {
		this.tbNewses = tbNewses;
	}

	public Set getTbResumes() {
		return this.tbResumes;
	}

	public void setTbResumes(Set tbResumes) {
		this.tbResumes = tbResumes;
	}

	public Set getTbUserRecruits() {
		return this.tbUserRecruits;
	}

	public void setTbUserRecruits(Set tbUserRecruits) {
		this.tbUserRecruits = tbUserRecruits;
	}

	public Set getTbComments() {
		return this.tbComments;
	}

	public void setTbComments(Set tbComments) {
		this.tbComments = tbComments;
	}
}
